name: Kemaskini Data Munsyid

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kod
      uses: actions/checkout@v4 # Dikemas kini ke v4

    - name: Sediakan Python
      uses: actions/setup-python@v5 # Dikemas kini ke v5
      with:
        python-version: '3.10'

    - name: Pasang Library Spotify
      run: |
        python -m pip install --upgrade pip
        pip install spotipy pandas

    - name: Jalankan Skrip Pengekstrakan
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      run: python fetch_data.py

    - name: Simpan Fail CSV Baru ke GitHub
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        git add munsyid_data.csv
        # Tambah semakan supaya bot tak ralat kalau tiada perubahan data
        git diff --quiet && git diff --staged --quiet || git commit -m "Automasi: Data Munsyid Dikemas Kini"
        git push
